# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kadas_gpkg_data_export_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KadasGpkgDataExportDialog(object):
    def setupUi(self, KadasGpkgDataExportDialog):
        KadasGpkgDataExportDialog.setObjectName("KadasGpkgDataExportDialog")
        KadasGpkgDataExportDialog.resize(569, 361)
        self.gridLayout = QtWidgets.QGridLayout(KadasGpkgDataExportDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(KadasGpkgDataExportDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 8, 0, 1, 2)
        self.label = QtWidgets.QLabel(KadasGpkgDataExportDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 1, 1, 1)
        self.labelExport = QtWidgets.QLabel(KadasGpkgDataExportDialog)
        self.labelExport.setWordWrap(True)
        self.labelExport.setObjectName("labelExport")
        self.gridLayout.addWidget(self.labelExport, 2, 0, 1, 2)
        self.listWidgetLayers = KadasGpkgLocalLayersList(KadasGpkgDataExportDialog)
        self.listWidgetLayers.setIconSize(QtCore.QSize(16, 16))
        self.listWidgetLayers.setObjectName("listWidgetLayers")
        self.gridLayout.addWidget(self.listWidgetLayers, 3, 0, 1, 2)
        self.labelCheckIcon = QtWidgets.QLabel(KadasGpkgDataExportDialog)
        self.labelCheckIcon.setMinimumSize(QtCore.QSize(16, 16))
        self.labelCheckIcon.setMaximumSize(QtCore.QSize(2, 16))
        self.labelCheckIcon.setPixmap(QtGui.QPixmap(":/images/themes/default/mIconSuccess.svg"))
        self.labelCheckIcon.setScaledContents(True)
        self.labelCheckIcon.setObjectName("labelCheckIcon")
        self.gridLayout.addWidget(self.labelCheckIcon, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelOutputFile = QtWidgets.QLabel(KadasGpkgDataExportDialog)
        self.labelOutputFile.setObjectName("labelOutputFile")
        self.horizontalLayout.addWidget(self.labelOutputFile)
        self.lineEditOutputFile = QtWidgets.QLineEdit(KadasGpkgDataExportDialog)
        self.lineEditOutputFile.setReadOnly(True)
        self.lineEditOutputFile.setObjectName("lineEditOutputFile")
        self.horizontalLayout.addWidget(self.lineEditOutputFile)
        self.buttonSelectFile = QtWidgets.QToolButton(KadasGpkgDataExportDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSelectFile.sizePolicy().hasHeightForWidth())
        self.buttonSelectFile.setSizePolicy(sizePolicy)
        self.buttonSelectFile.setObjectName("buttonSelectFile")
        self.horizontalLayout.addWidget(self.buttonSelectFile)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.labelWarnIcon = QtWidgets.QLabel(KadasGpkgDataExportDialog)
        self.labelWarnIcon.setMinimumSize(QtCore.QSize(16, 16))
        self.labelWarnIcon.setMaximumSize(QtCore.QSize(16, 16))
        self.labelWarnIcon.setPixmap(QtGui.QPixmap(":/images/themes/default/mIconWarning.svg"))
        self.labelWarnIcon.setScaledContents(True)
        self.labelWarnIcon.setObjectName("labelWarnIcon")
        self.gridLayout.addWidget(self.labelWarnIcon, 5, 0, 1, 1)
        self.groupBoxExtent = QtWidgets.QGroupBox(KadasGpkgDataExportDialog)
        self.groupBoxExtent.setCheckable(True)
        self.groupBoxExtent.setChecked(False)
        self.groupBoxExtent.setObjectName("groupBoxExtent")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxExtent)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelYMax = QtWidgets.QLabel(self.groupBoxExtent)
        self.labelYMax.setObjectName("labelYMax")
        self.gridLayout_2.addWidget(self.labelYMax, 1, 2, 1, 1)
        self.labelXMin = QtWidgets.QLabel(self.groupBoxExtent)
        self.labelXMin.setObjectName("labelXMin")
        self.gridLayout_2.addWidget(self.labelXMin, 0, 0, 1, 1)
        self.lineEditYMin = QtWidgets.QLineEdit(self.groupBoxExtent)
        self.lineEditYMin.setObjectName("lineEditYMin")
        self.gridLayout_2.addWidget(self.lineEditYMin, 1, 1, 1, 1)
        self.lineEditXMin = QtWidgets.QLineEdit(self.groupBoxExtent)
        self.lineEditXMin.setObjectName("lineEditXMin")
        self.gridLayout_2.addWidget(self.lineEditXMin, 0, 1, 1, 1)
        self.labelYMin = QtWidgets.QLabel(self.groupBoxExtent)
        self.labelYMin.setObjectName("labelYMin")
        self.gridLayout_2.addWidget(self.labelYMin, 1, 0, 1, 1)
        self.labelXMax = QtWidgets.QLabel(self.groupBoxExtent)
        self.labelXMax.setObjectName("labelXMax")
        self.gridLayout_2.addWidget(self.labelXMax, 0, 2, 1, 1)
        self.lineEditXMax = QtWidgets.QLineEdit(self.groupBoxExtent)
        self.lineEditXMax.setObjectName("lineEditXMax")
        self.gridLayout_2.addWidget(self.lineEditXMax, 0, 3, 1, 1)
        self.lineEditYMax = QtWidgets.QLineEdit(self.groupBoxExtent)
        self.lineEditYMax.setObjectName("lineEditYMax")
        self.gridLayout_2.addWidget(self.lineEditYMax, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBoxExtent, 7, 0, 1, 2)
        self.checkBoxClear = QtWidgets.QCheckBox(KadasGpkgDataExportDialog)
        self.checkBoxClear.setObjectName("checkBoxClear")
        self.gridLayout.addWidget(self.checkBoxClear, 1, 0, 1, 2)
        self.labelNote = QtWidgets.QLabel(KadasGpkgDataExportDialog)
        self.labelNote.setWordWrap(True)
        self.labelNote.setObjectName("labelNote")
        self.gridLayout.addWidget(self.labelNote, 5, 1, 1, 1)
        self.checkBoxPyramids = QtWidgets.QCheckBox(KadasGpkgDataExportDialog)
        self.checkBoxPyramids.setObjectName("checkBoxPyramids")
        self.gridLayout.addWidget(self.checkBoxPyramids, 6, 0, 1, 2)

        self.retranslateUi(KadasGpkgDataExportDialog)
        self.buttonBox.accepted.connect(KadasGpkgDataExportDialog.accept)
        self.buttonBox.rejected.connect(KadasGpkgDataExportDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(KadasGpkgDataExportDialog)

    def retranslateUi(self, KadasGpkgDataExportDialog):
        _translate = QtCore.QCoreApplication.translate
        KadasGpkgDataExportDialog.setWindowTitle(_translate("KadasGpkgDataExportDialog", "GPKG Data Export"))
        self.label.setText(_translate("KadasGpkgDataExportDialog", "<small><i>Layers already part of the output GeoPackage are disabled.</i></small>"))
        self.labelExport.setText(_translate("KadasGpkgDataExportDialog", "Add the following local layers to the GeoPackage:"))
        self.labelOutputFile.setText(_translate("KadasGpkgDataExportDialog", "Output file:"))
        self.buttonSelectFile.setText(_translate("KadasGpkgDataExportDialog", "Browse"))
        self.groupBoxExtent.setTitle(_translate("KadasGpkgDataExportDialog", "Restrict extent to export:"))
        self.labelYMax.setText(_translate("KadasGpkgDataExportDialog", "Y Max.:"))
        self.labelXMin.setText(_translate("KadasGpkgDataExportDialog", "X Min.:"))
        self.labelYMin.setText(_translate("KadasGpkgDataExportDialog", "Y Min.:"))
        self.labelXMax.setText(_translate("KadasGpkgDataExportDialog", "X Max.:"))
        self.checkBoxClear.setText(_translate("KadasGpkgDataExportDialog", "Clear existing GeoPackage before exporting"))
        self.labelNote.setText(_translate("KadasGpkgDataExportDialog", "<html><head/><body><p><span style=\" font-size:small; font-style:italic;\">Layers larger than 50 MB are deselected by default.</span></p></body></html>"))
        self.checkBoxPyramids.setText(_translate("KadasGpkgDataExportDialog", "Generate pyramids (slow)"))
from .kadas_gpkg_local_layers_list import KadasGpkgLocalLayersList
